# REQUIRED Either set them directly here or export them into the environment
# app_base_url:       # [REQUIRED]
# jwt_shared_secret:  # [REQUIRED]

# The following have defaults relative to where the application has been installed
# content_dir:  <install-dir>/var
# log_dir:      <install-dir>/log

# These defaults can be overridden by the environment or hard coded here directly
Dhcp_system_dir:          /etc/dhcp/dhcpd.metal-server
Initrd_system_dir:        /var/lib/tftpboot/boot
Kernel_system_dir:        /var/lib/tftpboot/boot
Kickstart_system_dir:     /var/www/kickstarts
Legacy_system_dir:        /var/lib/tftpboot/pxelinux.cfg
Uefi_system_dir:          /var/lib/tftpboot/efi
dhcpd_is_running_command: systemctl status dhcpd.service
restart_dhcpd_command:    systemctl restart dhcpd.service
validate_dhcpd_command:   dhcpd -t -cf /etc/dhcp/dhcpd.conf

# The following are used to enable different features within the application
# Setting the value to anything but 'true' will result in the feature being disabled
enable_dhcp:      'true'
enable_kickstart: 'true'
enable_netboot:   'true'

# Settings used by RSpec
test:
  app_base_url:             http://127.0.0.1
  jwt_shared_secret:        SOME_TEST_TOKEN
  content_dir:              /tmp/metal-server-spec/content
  Dhcp_system_dir:          /tmp/metal-server-spec/dhcpd.metal-server
  Initrd_system_dir:        /tmp/metal-server-spec/tftpboot/boot
  Kernel_system_dir:        /tmp/metal-server-spec/tftpboot/boot
  Kickstart_system_dir:     /tmp/metal-server-spec/www/kickstarts
  Legacy_system_dir:        /tmp/metal-server-spec/tftpboot/pxelinux.cfg
  Uefi_system_dir:          /tmp/metal-server-spec/tftpboot/efi
  dhcpd_is_running_command: echo Initial Test DHCP Is Running Command
  restart_dhcpd_command:    echo Initial Test DHCP Restart Command
  validate_dhcpd_command:   echo Initial Test DHCP Validation Command

# Alternative path settings. This is to prevent polluting the root file system
# during development
development:
  app_base_url:         http://127.0.0.1
  jwt_shared_secret:    SOME_DEVELOPMENT_TOKEN
  log_dir:              /var/metal-server/log
  content_dir:          /var/metal-server/content
  Dhcp_system_dir:      /var/metal-server/dhcpd.metal-server
  Initrd_system_dir:    /var/metal-server/tftpboot/boot
  Kernel_system_dir:    /var/metal-server/tftpboot/boot
  Kickstart_system_dir: /var/metal-server/www/kickstarts
  Legacy_system_dir:    /var/metal-server/tftpboot/pxelinux.cfg
  Uefi_system_dir:      /var/metal-server/tftpboot/efi

